// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvmhpditdxcwfcekugcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2bWhwZGl0ZHhjd2ZjZWt1Z2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODI1NjYsImV4cCI6MjA2OTA1ODU2Nn0.BwjrKaXS2XDEV4XkgW-8aNsEcUhg7Mp0cz7X46EKmm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});